### ISSUE TITLE
Unity Android Adapters Bugs

### ISSUE THREAD

**Issue by OguzhanKuloglu** [mopub/mopub-unity-mediation#28]
1- some missing aar and jar and files on Android side.
  
2. **Fill in the below template as detailed as possible:**
    * **Ad Format** :  Rewarded Video
    * **Platform**    :  Unity on Android side
    * **MoPub SDK Version** : 5.5
       
Atteched and AndroidStudio logs and Unity/asset/plugins/android side 
![screen shot 2019-02-19 at 13 28 49](https://user-images.githubusercontent.com/35737793/53008395-59c7c780-344a-11e9-8911-490389a89d8c.png)

![androidlogs](https://user-images.githubusercontent.com/35737793/53008296-208f5780-344a-11e9-9d3f-de3b568bd6f9.png)

[AndroidLogCat.txt](https://github.com/mopub/mopub-unity-mediation/files/2879523/AndroidLogCat.txt)

**Comment by chauduyphanvu1** [comment]
@OguzhanKuloglu - from the log it looks like it's complaining about the Chartboost SDK not found. This is expected because Chartboost is not a supported network via our Unity SDK Manager, so you will need to download and import the Chartboost SDK separately. The SDK Manager only downloads the Chartboost adapters (and adapters from any unsupported networks that are not available for download from JCenter or CocoaPods).

Vu Chau
MoPub SDK Team

**Comment by OguzhanKuloglu** [comment]
@chauduyphanvu1 But I didn't download for iOS side and mopub showing chartboost ads in iOS side.
One more question should I download chartboost sdk for android sdk or unity sdk?

**Comment by chauduyphanvu1** [comment]
We package both Android and iOS adapters together in one .unitypackage archive for unsupported networks. The iOS piece that you see is probably coming from the adapter .unitypackage. [Here's](https://github.com/mopub/mopub-unity-mediation/blob/master/unity-packages/MoPub-Chartboost-Adapters-prod-1.0.2-Android.7.3.1.1-iOS.7.3.0.4.unitypackage) the actual package.

You will download the Chartboost SDK for Android since we mediate Android/iOS SDKs from mediation ad networks.

**Comment by OguzhanKuloglu** [comment]
@chauduyphanvu1 Hi again, we just give up about chartboost because When I try download chartboost sdk for android.Android studio has some merge problem.

Now I'm trying to rewardedAds with admob and unityAds.But When I try make build in android studio still showing some .jar files missing like this 

 So what I'm missing now? I just did everything right.
![screen shot 2019-02-21 at 13 40 48](https://user-images.githubusercontent.com/35737793/53163068-5b29f900-35de-11e9-8eba-41be70817e48.png)

**Comment by chauduyphanvu1** [comment]
@OguzhanKuloglu - what was the error message you received for Chartboost? The expectation is that network SDKs are imported to the Unity project ([step  7](https://developers.mopub.com/docs/unity/getting-started/#integrate-the-plugin-and-mediation-adapters)), so you shouldn't be getting any Android Studio issues at this time. Could you confirm how you import network SDKs?

From the log one of the lines indicates a native ad class was in use. Are you making a native ad request? If so, we don't support native ad at this time. Other than that, please attach a sample project with which you saw the errors and we'll be happy to take a closer look!

**Comment by rsatrasala** [comment]
Please re-open if needed. Thank you.
