### ISSUE TITLE
UnityAds Adapters and Cocoapods

### ISSUE THREAD

**Issue by daCelky** [mopub/mopub-unity-mediation#32]
Hi ! I recently update my app to MoPub 5.5 and currently running into this error while building for iOS : 

None of your spec sources contain a spec satisfying the dependency: `MoPub-UnityAds-Adapters/Network (= 3.0.1.0)`.

It seems that the latest version of UnityAds available in Cocoapods.org is 3.0.0, is there any way to get the 3.0.1 on it ? Should I add other repository sources in my Cocoapods settings?

Thanks in advance, atm I just downgrade everything to 3.0.0.4 in order to build.

**Comment by dravyan** [comment]
Hi @daCelky,
  Thank you for your note. Unfortunately UnityAds has not made their SDK version 3.0.1 available on Cocoapods. Because of this you are seeing the issue. Since they do not have ETA yet on the 3.0.1 SDK pods availability, we have rolled back the adapter release. If you try downloading now, you should be able to get 3.0.0.4 adapters and 3.0.0 SDK and should successfully build.

Thanks,
Dravya Nataraj
MoPub SDKTeam
